FROM node:18.17.1
RUN mkdir /workdir &&  mkdir workdir/app 
WORKDIR /workdir
COPY workdir/package*.json workdir/
RUN npm install -g npm@9.8.1
RUN npm install -g @angular/cli@16.1
# Node 16.16 LTS, Alpine Linux is a small distribution image
#FROM node:16.16-alpine3.15

#WORKDIR /app

#COPY package*.json ./

#RUN npm install

# Copy all files to the work dir
#COPY . . 

#EXPOSE 4200

#CMD ["npm", "start"]
